# Custom Layers

In [1]:
import torch
from torch import nn
from torch.nn import functional as F

## Layers without Parameters

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

C:\Users\gprak\anaconda3\Lib\site-packages\torch\nn\modules\lazy.py:181: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [5]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(7.2177e-09, grad_fn=<MeanBackward0>)

## Layers with Parameters

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [7]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 1.5291,  0.2008, -0.3794],
        [ 2.1270, -0.1900,  1.5953],
        [-1.6322,  0.4612,  0.4223],
        [-0.8702, -0.5991, -0.8020],
        [-1.3946,  1.3932, -0.7781]], requires_grad=True)

In [8]:
linear(torch.rand(2, 5))

tensor([[0.0000, 2.5631, 0.0000],
        [0.3047, 1.7030, 0.0000]])

In [9]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.6784],
        [0.0000]])